Plant rechance
rschurade/Ingnomia pull request #137
Opened 2021-01-05 03:38 UTC by Daynvheur

Got chances >1 working
Got chances <1 working
Got chances Y*rand()+X working
Chances >100 no longer require 100+ sql lines of "0.0" chance.

Consider this PR as complete, but taking this up to the `Set up Game` ui would be awesome.

2021-01-05 08:56 UTC, Ext3h requested changes

2021-01-05 08:56 UTC, Ext3h commented on src/game/plant.cpp
> +			auto chanceValMax  = harvItem.value( "MaxChance" );
Use the getters to extract the contained value from the `QVariant`. Do *not* use `QVariant::d` to access the implementation details!

2021-01-05 08:56 UTC, Ext3h commented on src/game/plant.cpp
> +						);
Nested ternary terms are pretty much unreadable.  Not just that, but the logic for chanceMax / chanceMin does not even do what you intended it to do. If you thought "min = 3, max = 7" is going to give you something between 3-7 items, trace back what actually happened.

2021-01-05 08:56 UTC, Ext3h commented on src/game/plant.cpp
> +					auto ra = ( rand() % 100 ) / (double)100; // Type "ra" same as "chance"
Don't put type information in comments. It does not belong there. Either you use `auto`, then the type better be obvious from context, or you write out the type name explicitly.

2021-01-05 08:56 UTC, Ext3h commented on src/game/plant.cpp
> +					while ( chance-- > ra ) // Eat 1 "chance" for every "ra" looped ; permits 1.5 chance to generate 1 + "maybe 1" depending on ra.
Incrementing floating point types by use of postfix operator is bad style. You get rounding errors, rapidly, due to floating point implementation details.

Also avoid comments like that. Especially with fictional values, which are not recognizable as such.

If it feels like the `--` would had been missed easily when reading, then do not perform it inline but put it in a separate statement.

2021-01-05 08:56 UTC, Ext3h commented on content/db/ingnomia.db.sql
> +	"MaxChance" DOUBLE,
Do we need these additional fields *at all*? I suppose this is for allowing a higher range in the number of items, but then we wouldn't need the single `Chance` field at all.

A higher range in the number of produced items also clashes with the goal of ideally only ever having close to 1 item per tile (outside stockpile), so this doesn't really have much of a use.

Please do not introduce redundant mechanisms.

2021-01-05 10:53 UTC, Daynvheur commented on content/db/ingnomia.db.sql
> +	"MaxChance" DOUBLE,
There is strong difference between "fixed 1.5" and "min 0 + max 3", and one would want either depending on the context.

There is no need in artificially limit gameplay generation because of core game issue, as each new object could be placed at a nearby (free) `pos`. You're right that balance could be in favor of <1 chances, but that's not a technically good reason to duplicate sql lines (40% of Plants_OnHarvest_HarvestedItem where `0.0` chances followed by `0.5` or `0.3`!). Actually speaking, seeds were already 2-packed generated on the same `pos`.

Don't get me wrong: adding multiple rows of the same entry in a db is a bad idea.

I'm not introducing redundant mechanisms.

2021-01-05 11:26 UTC, Ext3h commented on content/db/ingnomia.db.sql
> +	"MaxChance" DOUBLE,
Adding multiple rows in the DB has effectively no impact on complexity. Introducing redundant columns where one can be expressed by a combination of others is pretty much the definition of redundant logic.

2021-01-05 11:50 UTC, Daynvheur reviewed
Reviewed everything for now, the "redundancy" topic stays closed.

2021-01-05 11:50 UTC, Daynvheur commented on src/game/plant.cpp
> +						);
Changing that (cutting ternary in pieces, and re-do the calculations).

2021-01-05 11:50 UTC, Daynvheur commented on src/game/plant.cpp
> +					auto ra = ( rand() % 100 ) / (double)100; // Type "ra" same as "chance"
Where is the type commented..? It's obviously a `double`, the comment just states the type of `ra` should be same as `chance`.

2021-01-05 11:50 UTC, Daynvheur commented on src/game/plant.cpp
> +					while ( chance-- > ra ) // Eat 1 "chance" for every "ra" looped ; permits 1.5 chance to generate 1 + "maybe 1" depending on ra.
Okay for the separate statement, and dropping the comment.

2021-01-05 11:55 UTC, Daynvheur commented on content/db/ingnomia.db.sql
> +	"MaxChance" DOUBLE,
Changed that a little, considering "minChance" alone acts same as "Chance" alone, I dropped the former.
I kept "maxChance" as a separate concept, in a manner of formally express "0 to 1.5" gains in a more luck-based way than fixed "0.75".

Tell me if/how that feels wrong to you.

2021-01-05 12:00 UTC, rschurade commented on content/db/ingnomia.db.sql
> +	"MaxChance" DOUBLE,
Absolutely not a fan of this. What this can't model is something like 50% for a second item and 25% for a third item. Yes the current code doesn't really support this either because these are connected chance rolls but at least the DB supports it already. Though it remains tot be decided if in this example the 25% roll is completely omitted when the 50% roll fails or if it could still be considered..

2021-01-05 12:15 UTC, Daynvheur commented on content/db/ingnomia.db.sql
> +	"MaxChance" DOUBLE,
Didn't understand the three-items problem.

Wheat example:
```sql
INSERT INTO "Plants_OnHarvest_HarvestedItem" ("ID","Chance","ItemID","MaterialID") VALUES ('Wheat',0.0,'Grain','Wheat');
INSERT INTO "Plants_OnHarvest_HarvestedItem" ("ID","Chance","ItemID","MaterialID") VALUES ('Wheat',0.0,'Straw','Wheat');
INSERT INTO "Plants_OnHarvest_HarvestedItem" ("ID","Chance","ItemID","MaterialID") VALUES ('Wheat',0.0,'Seed','Wheat');
INSERT INTO "Plants_OnHarvest_HarvestedItem" ("ID","Chance","ItemID","MaterialID") VALUES ('Wheat',0.3,'Seed','Wheat');
```
becomes
```sql
INSERT INTO "Plants_OnHarvest_HarvestedItem" ("ID","Chance","MinChance","MaxChance","ItemID","MaterialID") VALUES ('Wheat',1,NULL,NULL,'Grain','Wheat');
INSERT INTO "Plants_OnHarvest_HarvestedItem" ("ID","Chance","MinChance","MaxChance","ItemID","MaterialID") VALUES ('Wheat',1,NULL,NULL,'Straw','Wheat');
INSERT INTO "Plants_OnHarvest_HarvestedItem" ("ID","Chance","MinChance","MaxChance","ItemID","MaterialID") VALUES ('Wheat',1.3,NULL,NULL,'Seed','Wheat');
```

Three-to-four items (counting duplicating seed) were generated before with 4 sql lines, three-to-four items are generated with 3 sql lines.

..?

2021-01-05 12:17 UTC, Daynvheur commented on content/db/ingnomia.db.sql
> +	"MaxChance" DOUBLE,
Chance to generate a new item based on the previous "consumed" chance of generating an item is a great evolution, that is easily implemented in a global job chance (efficiency), though that is not the purpose of this PR.

2021-01-05 12:43 UTC, Ext3h commented on content/db/ingnomia.db.sql
> +	"MaxChance" DOUBLE,
Don't get hold up on "chance" please.  Chance here is only a way of saying "there can't be 0.3 items, so we have to approximate that long-term by random numbers". For all I care, we could even do that without random numbers by saying "every 3.3333 jobs produces deterministically an item", and it would have the same result for the user. If anything, even more stable so as there is no chance of punishing the user for having back luck.

Big variance doesn't provide much, except for being random for randomness sake. It's not even something the user will *see*, so there isn't even a feeling of reward associated with an especially high random roll.

2021-01-05 13:16 UTC, Daynvheur commented on content/db/ingnomia.db.sql
> +	"MaxChance" DOUBLE,
Without maxChance, what would be the purpose of this PR..?

2021-01-05 14:57 UTC, Daynvheur commented on content/db/ingnomia.db.sql
> +	"MaxChance" DOUBLE,
Okay, real talk, my point of view.
Plus side:
- ok for actual 1 chance generation (equiv to previous "0.0" lines)
- ok for actual 0.3 chance generation (equiv to lines following "0.0")
- ok for new (linear) 1.3 chance
- ok for 0.5 to 1.5 in one line
- ok for 0.1 to 0.6 in a second line
- ok for max 0.001 in a third line

Minus side:
- adds a column in the db table (reflected in code)
- is not a job overhaul (but might be complementary to -)
- is not a harvest overhaul (and don't intended to be), floating point harvesting is another topic (could depend on the number of  harvest jobs done to keep track of when another item would be generated, but the entire actual random system would be dropped anyway)
- partially defeated by any non-linear "chance", but that doesn't change from the actual system

What could I do to make this PR acceptable for you?

2021-01-05 15:01 UTC, Daynvheur commented on src/game/plant.cpp
> +			if ( chance.HasValue() )
`Null` and `0` have a totally different meaning, yet in this scenario they may share effects.
I'll take a second look at it.

2021-01-05 15:03 UTC, Daynvheur commented on src/game/plant.cpp
> +			Noesis::Nullable<double> chance = nullptr;
I was looking for the `double?` (nullable) type, that was all I found ; I'll eventually check for [some kind of null type](https://stackoverflow.com/questions/25555015/how-to-store-some-kind-of-null-in-c-double-or-int-variable), likely `std::numeric_limits<double>::quiet_NaN()`.

2021-01-05 15:11 UTC, Daynvheur commented on src/game/plant.cpp
> +				chance = ( chanceValMax.value<double>() - chance.GetValue() ) * ( rand() % 100 ) / 100.0 + chance.GetValue();
0 to 99 is actually a hundredth value span.
That prevents `[100]/100` to happen, but it's the `rand` game of choices.
Do you prefer:
- `rand` modulo `101`? _([0-100]/100)_
- or divide it by `99`? _([0-99]/99)_
- or `+1` the `rand` value? _([1-100]/100)_

Tell me which you prefer, otherwise I'll leave it as-is.

2021-01-07 10:17 UTC, Daynvheur commented
Stale.

2021-01-07 10:17 UTC, closed without merging

2021-01-07 10:20 UTC, Daynvheur commented on content/db/ingnomia.db.sql
> +	"MaxChance" DOUBLE,
Nothing.