Fix crash when pressing spawn trader in debug menu.
rschurade/Ingnomia pull request #170
Opened 2021-01-27 20:10 UTC by condac

This one is a bit strange. On steam build I do not get a crash. But with exact the same git hash 16d22651 compiled my self in linux I do get a crash (with the same save game)
```
./Ingnomia
Ingnomia: /home/a/ingnomia/Ingnomia/src/base/../base/../base/position.h:61: Position::Position(QVariant): Assertion `sl.size() == 3' failed.
Aborted (core dumped)
```

2021-01-27 21:09 UTC, Ext3h commented
Steam build doesn't have assertions enabled, but that's a bug to be sure.

Something is twisted around the usage of `getEventLocation` though. It should only be used when the event is processed, as it performs collision checks which are can't (must not) be performed ahead of time.

It should had been used in uniformly in `EventManager::executeEvent` only.

2021-01-28 18:00 UTC, condac commented
I get same crash/assert when random goblin invation is triggered by the game.

2021-01-28 18:06 UTC, Ext3h commented
Like I said, expected as `getEventLocation` is used inconsistently, and should be used in only a single place.

2021-01-31 08:55 UTC, Ext3h requested changes

2021-01-31 08:55 UTC, Ext3h commented on src/game/eventmanager.cpp
> +	getEventLocation( data );
`getEventLocation` should only be used in exactly one location, and that is in the preamble of `EventManager::executeEvent`.

2021-01-31 09:43 UTC, condac commented on src/game/eventmanager.cpp
> +	getEventLocation( data );
New commit with a beter solution, check if the location is pre set and if not set it during the event. There might be events in the future where you want it to take place on a pre defined place so I did not want to butcher the pre defined position. 
Also there was no else in the getEventLocation so incase there is some undefined items in DB it will not crash.

2021-01-31 09:50 UTC, Ext3h commented on src/game/eventmanager.cpp
> +	getEventLocation( data );
I understand what you mean, but even if a position was predefined, we must validate it before using it. It is likely to have been invalidated since the even was queued. That whole validation thing is also missing in `getEventLocation` but should be in there.

2021-01-31 12:13 UTC, condac commented
I messed up my git with commits so i squashed everything.

2021-01-31 12:48 UTC, condac commented
This is timeconsuming to test when waiting for events not triggered by debug menu but looks stable now.

2021-08-01 14:05 UTC, Ext3h commented
Spawn logic was replaced

2021-08-01 14:05 UTC, closed without merging